#!python

### #!/usr/bin/env python3
import os
import sys
from glob import glob
from snakemake.utils import read_job_properties
import pdb

configfile: "config.freeze.json"

def get_inputs(wildcards):
    inputs = []   
    pattern = "/global/scratch2/Rockfish/Genomes/merqury/{species}/{sample}.meryl.DONE"
    for s in config["SAMPLES"]:
        species, sample = s.split("/")
        inputs.append(pattern.format(species=species,  
                                     sample=sample))
    return inputs

rule all: 
    input: 
          get_inputs

rule meryl_db:
  input: 
    fwd=lambda wildcards: glob("/global/scratch2/Rockfish/Genomes/sequencing/illumina/fastq/{species}/{sample}/*_R1_*.fastq.gz"\
                        .format(species=wildcards.species,sample=wildcards.sample)),
    rev=lambda wildcards: glob("/global/scratch2/Rockfish/Genomes/sequencing/illumina/fastq/{species}/{sample}/*_R2_*.fastq.gz".\
                        format(species=wildcards.species,sample=wildcards.sample)),
  output: 
    #meryldb="/global/scratch2/Rockfish/Genomes/merqury/{species}/illumina_meryldb/merylIndex",
    catcher="/global/scratch2/Rockfish/Genomes/merqury/{species}/{sample}.meryl.DONE",
  params:
        slurm_opts=lambda wildcards: "-n 1 " \
                                     "--time 45:00:00 " \
                                     "-A co_genomicdata " \
                                     "-p savio3_bigmem --qos=savio_lowprio " \
                                     "-e /global/scratch2/Rockfish/Genomes/merqury/logs/meryl_{species}.log " \
                                     "-J meryl_{species} " \
                                     .format(species=wildcards.species)    
  run:
    shell("""
        module load merqury;
        cd /global/scratch2/Rockfish/Genomes/merqury/{species}/;
        zcat {inputfq1} {inputfq2} >{species}.fq && gzip {species}.fq;
        meryl count k=21 memory=360 threads=32 \
                {species}.fq.gz output illumina_meryldb.meryl;
        rm -f {species}.fq.gz && touch {sample}.meryl.DONE;
        """.format(inputfq1=input.fwd, inputfq2=input.rev,
                   species=wildcards.species, sample=wildcards.sample))


