#!python
#!/usr/bin/env python3
import os
import sys
from glob import glob
from snakemake.utils import read_job_properties
import pdb

configfile: "config.freeze.json"
work_dir = "/global/scratch2/Rockfish/Genomes/FREEZE"

def get_inputs(wildcards):
    inputs = []    
    pattern = "{work_dir}/{assembler}/{species}/REPEAT/referencegenome.fasta.softmask.FASTA"
    for s in config["SAMPLES"]:
        assembler, species = s.split("/")
        inputs.append(pattern.format(species=species, assembler=assembler, work_dir=work_dir))
    return inputs

rule all: 
    input: 
          get_inputs

rule repeatsoftmask:
    input:
        asmb="{work_dir}/{assembler}/{species}/referencegenome.fasta"
    output:
        rpmtbl="{work_dir}/{assembler}/{species}/REPEAT/referencegenome.fasta.tbl",
        rpmout="{work_dir}/{assembler}/{species}/REPEAT/referencegenome.fasta.out",
        rpmbed="{work_dir}/{assembler}/{species}/REPEAT/referencegenome.fasta_rm.bed",
        rpmsortbed="{work_dir}/{assembler}/{species}/REPEAT/repeats.sorted.bed",
        rpmmergebed="{work_dir}/{assembler}/{species}/REPEAT/repeats.merged.bed",
        softmask="{work_dir}/{assembler}/{species}/REPEAT/referencegenome.fasta.softmask.FASTA"
    params:
        slurm_opts=lambda wildcards: "-N 1 " \
                                    "--time 3-00:00:00 " \
                                    "-A co_genomicdata " \
                                    "--qos=savio_lowprio " \
                                    "-p savio3_bigmem,savio_bigmem,savio2_bigmem " \
                                    "-o {work_dir}/logs/RPM_{species}.log " \
                                    "-J RPM_{species} " \
                                    .format(species=wildcards.species, work_dir=work_dir)
    run:
        masker="""
        module load bedtools repeatmasker ;
        RepeatMasker -norna -gff -xsmall \
                -pa 32 -div 50 -species vertebrates \
                -dir {work_dir}/{assembler}/{species}/REPEAT/ \
                {input_asmb};
        python3 /global/scratch2/Software/RepeatMasker_new/RM2Bed.py \
                --out_dir {work_dir}/{assembler}/{species}/REPEAT/ \
                --out_prefix referencegenome.fasta {output_rpmout};
        sort -k1,1 -k2,2n {output_rpmbed} >{output_sortbed};        
        bedtools merge -i {output_sortbed} >{output_mergebed};
        bedtools maskfasta -soft -fi {input_asmb} -bed {output_mergebed} -fo {output_softmask};
        """.format(input_asmb=input.asmb, output_rpmout=output.rpmout,\
                output_rpmbed=output.rpmbed, output_sortbed=output.rpmsortbed,\
                output_bed=output.rpmbed, output_mergebed=output.rpmmergebed, output_softmask=output.softmask,\
                assembler=wildcards.assembler, species=wildcards.species, work_dir=work_dir)
        shell(masker)

